sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t shameersn/docker-react -f Dockerfile.dev .

scrips:
  - docker run -e CI=true shameersn/docker-react npm run test -- --coverage
